services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - PORT=3000
      - DB_PATH=./data/data.db
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
